---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

name: Code scan

on:
  push:
    branches:
      - 'master'
      - 'dev'

  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

jobs:

  build_and_test:
    name: Run scanners

    outputs:
      job_status: ${{ job.status }}

    runs-on: ubuntu-latest

    steps:

      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: SonarCloud Scan
        id: sonarcloud_scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: >-
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.sources=.
            -Dsonar.verbose=true


      - name: Send notification on build completion
        uses: rest-gateway/notification-action@1.0.9
        if: always()
        with:
          message: |
            <b>Workflow:</b>   ${GITHUB_WORKFLOW}
            <b>Repository:</b> ${GITHUB_REPOSITORY}

            <b>Matrix:</b>
            Ref: ${{ env.PLANNED_VERSION_COMMIT }}

            <b>Outcome:</b> 
            sonarcloud_scan: ${{ steps.sonarcloud_scan.outcome }}

            <b>Run:</b> <code>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}</code>
            <b>Artifact repo:</b> ${{ secrets.ARTIFACTORY_REPO_URL }}

          recipient: "${{ secrets.NOTIFICATIONS_DEFAULT_RECIPIENT }}"
          rest_gateway_url: "${{ secrets.REST_GATEWAY_API_URL }}"
          rest_gateway_token: "${{ secrets.REST_GATEWAY_TOKEN }}"
          rest_gateway_bot_name: "${{ secrets.REST_GATEWAY_BOT_NAME }}"


  after_build:
    name: After build process
    runs-on: ubuntu-latest

    if: always()

    needs:
      - build_and_test

    steps:

      - name: Send notification on all builds finish
        uses: rest-gateway/notification-action@1.0.9
        with:
          message: |
            <b>Workflow:</b>   ${GITHUB_WORKFLOW}
            <b>Repository:</b> ${GITHUB_REPOSITORY}

            <b>Build and test:</b>
            Status: ${{ needs.build_and_test.outputs.job_status }}

          recipient: "${{ secrets.NOTIFICATIONS_DEFAULT_RECIPIENT }}"
          rest_gateway_url: "${{ secrets.REST_GATEWAY_API_URL }}"
          rest_gateway_token: "${{ secrets.REST_GATEWAY_TOKEN }}"
          rest_gateway_bot_name: "${{ secrets.REST_GATEWAY_BOT_NAME }}"


...
